@echo off
:: Display information
echo This script will remove *.pyc files. These files are generated by Python, but they can cause conflicts after an upgrade. It's safe to remove them, because they will be regenerated.
echo Press enter to continue, or CTRL + C to quit.
pause

cd ..\
del /S *.pyc
