#!/usr/bin/env bash

# The installer command (Homebrew, sudo installer -pkg) sets COMMAND_LINE_INSTALL and cannot show a dialog
if [[ -n $COMMAND_LINE_INSTALL ]]
then
    exit 0;
fi

dialogText=`osascript -e 'set dialogText to button returned of (display dialog "Installation complete. Start Tautulli?" buttons {"Start", "Close"})'`;
if [[ $dialogText == 'Start' ]]
then
    open /Applications/Tautulli.app
else
    exit 0;
fi
